extent.reporter.spark.start=true
extent.reporter.spark.out=reports/extentReport.html

extent.reporter.spark.vieworder=dashboard,test,category,exception

systeminfo.user=Automation Tester
systeminfo.os=Windows
systeminfo.browser=Chrome
systeminfo.project=Amazon Automation